# Generated by Django 4.1.7 on 2023-03-30 18:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    replaces = [
        ("goods", "0001_initial"),
        ("goods", "0002_initial"),
        ("goods", "0003_alter_dish_added_date"),
        ("goods", "0004_alter_dish_added_date"),
        ("goods", "0005_alter_dish_added_date_alter_dish_description_and_more"),
        ("goods", "0006_alter_dish_added_date"),
        ("goods", "0007_alter_dish_added_date"),
        ("goods", "0008_comment"),
        ("goods", "0009_alter_comment_options_remove_comment_added_by_and_more"),
        ("goods", "0010_comment_level_comment_lft_comment_rght_and_more"),
        ("goods", "0011_comment_added_by"),
        ("goods", "0012_dish_times_bought"),
        ("goods", "0013_category_dish_category"),
        ("goods", "0014_alter_dish_added_by_alter_dish_added_date"),
        ("goods", "0015_alter_dish_added_date"),
        ("goods", "0016_alter_dish_added_by"),
        ("goods", "0017_alter_dish_added_by"),
        ("goods", "0018_alter_dish_added_by"),
        ("goods", "0019_alter_dish_added_by"),
        ("goods", "0020_alter_dish_added_by"),
        ("goods", "0021_remove_dish_added_date_category_added_by_and_more"),
        ("goods", "0022_alter_dish_added_by"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0003_remove_useraddress_mobile_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/not-found.png",
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "added_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Added"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Price"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Available for users?"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.vendor",
                        verbose_name="Vendor",
                    ),
                ),
                (
                    "times_bought",
                    models.IntegerField(default=0, verbose_name="Times bought"),
                ),
            ],
            options={
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("comment_text", models.TextField(blank=True, default="")),
                (
                    "dish",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="goods.dish",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="goods.comment",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=None, editable=False)),
                ("lft", models.PositiveIntegerField(default=None, editable=False)),
                ("rght", models.PositiveIntegerField(default=None, editable=False)),
                (
                    "tree_id",
                    models.PositiveIntegerField(
                        db_index=True, default=None, editable=False
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goods.category",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.vendor",
                verbose_name="Vendor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.vendor",
                verbose_name="Vendor",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.vendor",
                verbose_name="Vendor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.vendor",
                verbose_name="Vendor",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.vendor",
                verbose_name="Vendor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendor",
            ),
        ),
        migrations.RemoveField(
            model_name="dish",
            name="added_date",
        ),
        migrations.AddField(
            model_name="dish",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
