# Generated by Django 4.1.7 on 2023-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
