# Generated by Django 4.1.7 on 2023-03-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_comment_level_alter_comment_lft_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
