# Generated by Django 4.0.4 on 2022-05-04 09:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_dish_added_date_alter_dish_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="added_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 5, 4, 12, 34, 50, 252048),
                verbose_name="Added",
            ),
        ),
    ]
