# Generated by Django 4.0.4 on 2022-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_alter_comment_options_remove_comment_added_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="tree_id",
            field=models.PositiveIntegerField(
                db_index=True, default=None, editable=False
            ),
            preserve_default=False,
        ),
    ]
