# Generated by Django 4.0.4 on 2022-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_comment_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="times_bought",
            field=models.IntegerField(default=0, verbose_name="Times bought"),
        ),
    ]
