# Generated by Django 4.0.4 on 2022-06-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_dish_times_bought"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="goods.category"
            ),
        ),
    ]
