# Generated by Django 4.0.4 on 2022-07-15 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0014_alter_dish_added_by_alter_dish_added_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="added_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, null=True, verbose_name="Added"
            ),
        ),
    ]
