version: 2
updates:
  - package-ecosystem: 'pip' # See documentation for possible values
    directory: '/backend' # Location of package manifests
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
