repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: requirements-txt-fixer
        name: Fix requirements.txt files
      - id: end-of-file-fixer
        name: Fix end of files
      - id: no-commit-to-branch
        name: Checking no commit to branch
      - id: requirements-txt-fixer
        name: Fixing end of files
      - id: detect-aws-credentials
        name: Cheching AWS credentials
      - id: check-yaml
        name: Checking yaml
      - id: check-toml
        name: Checking toml
      - id: check-json
        name: Checking json
        exclude: ^(frontend/.vscode|frontend/tsconfig*)
      - id: check-ast
        name: Checking Python syntax
      - id: check-added-large-files
        name: Checking for large files

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Black
        args: ['--line-length', '99']

  # There should be checks for uncreated migrations.

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        name: Mypy type checks
        additional_dependencies: ['django-stubs']
        entry: bash -c "export DJANGO_SETTING_MODULE='src.settings'"
        args: ['--config-file', 'backend/setup.cfg', '--no-incremental']

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['backend/src', '--config', 'backend/tox.ini']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: ['--config', 'frontend/.prettierrc', '--ignore-path', 'frontend/.prettierignore']
