version: '3.4'

services:
  db:
    image: postgres
    container_name: hinkal-store-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: backend/prod.env
    networks:
      - marketplace-hinkal-network

  backend:
    image: dborodin836/hinkal-backend
    container_name: hinkal-store-backend
    command: bash -c "cd backend
      && python3 manage.py wait_for_db
      && python3 manage.py migrate
      && python3 manage.py loaddata fixtures/groups.json
      && python3 manage.py loaddata fixtures/demo_data.json
      && python3 manage.py sadmin
      && python3 manage.py collectstatic --noinput
      && gunicorn --bind :8000 --workers 3 src.wsgi --env DJANGO_SETTINGS_MODULE=src.settings"
    restart: unless-stopped
    volumes:
      - .:/code
      - ./static_files:/code/backend/static
    networks:
      - marketplace-hinkal-network
    env_file: backend/prod.env
    environment:
      - ENV=PROD
    depends_on:
      - db

  nginx:
    image: dborodin836/hinkal-nginx
    container_name: hinkal-store-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - ./static_files:/home/app/staticfiles/
    ports:
      - '80:80'
    networks:
      - marketplace-hinkal-network
    depends_on:
      - backend

volumes:
  static_files:

networks:
  marketplace-hinkal-network:
    driver: bridge
