version: '3.4'

services:
  db:
    image: postgres
    container_name: marketplace-hinkal-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: backend/docker.env
    ports:
      - '5432:5432'
    networks:
      - marketplace-hinkal-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-hinkal-backend
    command: bash -c "cd backend
      && python3 manage.py wait_for_db
      && python3 manage.py migrate
      && python3 manage.py loaddata fixtures/groups.json
      && python3 manage.py sadmin
      && python3 manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - '8000:8000'
      - '80:4200'
    networks:
      - marketplace-hinkal-network
    env_file: backend/docker.env
    environment:
      - ENV=DOCKER
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.docker
    container_name: marketplace-hinkal-frontend
    restart: unless-stopped
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - '4200:80'
    networks:
      - marketplace-hinkal-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

networks:
  marketplace-hinkal-network:
    driver: bridge
