services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  backend:
    build: backend/
    command: bash -c "cd backend
                   && python3 manage.py wait_for_db
                   && python3 manage.py migrate
                   && python3 manage.py loaddata fixtures/groups.json
                   && python3 manage.py sadmin
                   && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "80:4200"
    environment:
      - ENV=PROD
    depends_on:
      - pgbouncer
  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_NAME}
      - DB_PORT=5432
      - LISTEN_PORT=6432
      - AUTH_TYPE=plain
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,dbuser
    ports:
      - "6432:6432"
    depends_on:
      - db
  frontend:
    build: frontend/
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "4200:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
