# Generated by Django 4.0.3 on 2022-03-10 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_ordered_date_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='order_if',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 14, 13, 50, 904827)),
        ),
    ]
