# Generated by Django 4.0.3 on 2022-03-10 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_order_if_discount_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 14, 25, 46, 78546)),
        ),
    ]
