# Generated by Django 4.0.3 on 2022-03-12 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermodifier_discount_added_by_order_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='modifier',
        ),
        migrations.AddField(
            model_name='order',
            name='modifier',
            field=models.ManyToManyField(null=True, to='orders.ordermodifier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 12, 51, 48, 231876)),
        ),
    ]
