# Generated by Django 4.0.3 on 2022-03-13 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_modifier_order_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(default='sample text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='sample text', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='modifier',
            field=models.ManyToManyField(to='orders.ordermodifier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 13, 41, 0, 203496)),
        ),
    ]
