# Generated by Django 4.0.3 on 2022-04-27 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_discount_added_by_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modifier',
            field=models.ManyToManyField(null=True, to='orders.ordermodifier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 23, 52, 59, 813576)),
        ),
    ]
