# Generated by Django 4.1.7 on 2023-03-31 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("contact", "0001_initial"),
        ("contact", "0002_alter_contact_added_date"),
        ("contact", "0003_alter_contact_added_date"),
        ("contact", "0004_alter_contact_added_date"),
        ("contact", "0005_alter_contact_added_date"),
        ("contact", "0006_alter_contact_added_date"),
        ("contact", "0007_remove_contact_added_date_contact_created_at_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("email", models.EmailField(max_length=254, verbose_name="Sender")),
                ("message", models.TextField(verbose_name="User's message")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
