# Generated by Django 4.1.7 on 2023-06-19 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("email", models.EmailField(max_length=254, verbose_name="Sender")),
                ("message", models.TextField(verbose_name="User's message")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
