# Generated by Django 4.0.3 on 2022-03-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='photos/2022/03/09/Black-Play-Button-PNG-Picture.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
