# Generated by Django 4.0.3 on 2022-03-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vendor_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
