# Generated by Django 4.0.3 on 2022-03-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_countries_country_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': "User's Address", 'verbose_name_plural': "User's Addresses"},
        ),
    ]
