# Generated by Django 4.0.3 on 2022-03-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
