# Generated by Django 4.0.3 on 2022-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_vendor_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
