# Generated by Django 4.0.3 on 2022-03-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 14, 11, 31, 529665)),
        ),
    ]
