# Generated by Django 4.0.3 on 2022-03-09 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_dish_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 11, 6, 2, 382142), verbose_name='Added'),
        ),
    ]
