# Generated by Django 4.0.3 on 2022-03-10 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_dish_added_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 13, 8, 31, 370721), verbose_name='Added'),
        ),
    ]
