# Generated by Django 4.0.3 on 2022-03-10 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_dish_options_dish_price_alter_dish_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 13, 17, 54, 30876), verbose_name='Added'),
        ),
    ]
