# Generated by Django 4.0.3 on 2022-04-27 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_vendor_name_vendor_biography'),
        ('goods', '0011_dish_is_active_alter_dish_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 17, 52, 39, 358586), verbose_name='Added'),
        ),
    ]
