# Generated by Django 4.0.4 on 2022-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
