# Generated by Django 4.1.7 on 2023-03-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="modifier",
        ),
        migrations.DeleteModel(
            name="OrderModifier",
        ),
    ]
