# Generated by Django 4.0.4 on 2022-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="details",
            field=models.ManyToManyField(to="orders.orderitem"),
        ),
    ]
