# Generated by Django 4.0.4 on 2022-08-12 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
