# Generated by Django 4.0.4 on 2022-06-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_useraddress_mobile_and_more'),
        ('orders', '0011_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryorder',
            name='ordered_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
    ]
