# Generated by Django 4.0.4 on 2022-06-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_useraddress_mobile_and_more'),
        ('orders', '0012_alter_temporaryorder_ordered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='temporaryorder_ptr',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.DeleteModel(
            name='TemporaryOrder',
        ),
    ]
